spring:
  quartz:
    scheduler-name: mySpringbootQuartz
    job-store-type: jdbc
    overwrite-existing-jobs: true
    jdbc:
      comment-prefix: '#'
      initialize-schema: always
    wait-for-jobs-to-complete-on-shutdown: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=true&false&useSSL=false
    username: root
    password: root

  jpa:
    show-sql: true
server:
  port: 8086

logging:
  level:
    com.nalq.helloquartz: debug
  pattern:
    dateformat: HH:mm:ss